-- MySQL Script generated by MySQL Workbench
-- Sun Nov  6 01:21:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Codigo` NVARCHAR(100) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Soporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Soporte` (
  `Id` INT NOT NULL,
  `TipoSoporte` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ticket` (
  `CodigoUsuario` NVARCHAR(100) NOT NULL,
  `TipoSoporte` VARCHAR(100) NOT NULL,
  `Cliente` VARCHAR(45) NOT NULL,
  `DescripcionSolicitud` VARCHAR(45) NOT NULL,
  `DescripcionRespuesta` VARCHAR(45) NOT NULL,
  `Precio` DECIMAL(9,2) NOT NULL,
  `Impuesto` DECIMAL(9,2) NOT NULL,
  `Descuento` DECIMAL(9,2) NOT NULL,
  `Total` DECIMAL(9,2) NOT NULL,
  `Fecha` DATETIME NULL,
  PRIMARY KEY (`CodigoUsuario`),
  CONSTRAINT `FK_Ticket_Usuario`
    FOREIGN KEY (`CodigoUsuario`)
    REFERENCES `mydb`.`Usuario` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
